[0.000000] (-) TimerEvent: {}
[0.001606] (-) JobUnselected: {'identifier': 'py_srvcli'}
[0.001909] (-) JobUnselected: {'identifier': 'raspicam_node'}
[0.002073] (follow_objects) JobQueued: {'identifier': 'follow_objects', 'dependencies': OrderedDict()}
[0.002385] (follow_objects) JobStarted: {'identifier': 'follow_objects'}
[0.098448] (-) TimerEvent: {}
[0.199198] (-) TimerEvent: {}
[0.299891] (-) TimerEvent: {}
[0.401652] (-) TimerEvent: {}
[0.502951] (-) TimerEvent: {}
[0.604139] (-) TimerEvent: {}
[0.704773] (-) TimerEvent: {}
[0.805438] (-) TimerEvent: {}
[0.906169] (-) TimerEvent: {}
[1.006961] (-) TimerEvent: {}
[1.107769] (-) TimerEvent: {}
[1.208462] (-) TimerEvent: {}
[1.309093] (-) TimerEvent: {}
[1.409807] (-) TimerEvent: {}
[1.463611] (follow_objects) StderrLine: {'line': b'Traceback (most recent call last):\n  File "/usr/lib/python3/dist-packages/colcon_core/executor/__init__.py", line 91, in __call__\n    rc = await self.task(*args, **kwargs)\n  File "/usr/lib/python3/dist-packages/colcon_core/task/__init__.py", line 93, in __call__\n    return await task_method(*args, **kwargs)\n  File "/usr/lib/python3/dist-packages/colcon_ros/task/ament_python/build.py", line 51, in build\n    setup_py_data = get_setup_data(self.context.pkg, env)\n  File "/usr/lib/python3/dist-packages/colcon_core/task/python/__init__.py", line 20, in get_setup_data\n    return dict(pkg.metadata[key](env))\n  File "/usr/lib/python3/dist-packages/colcon_ros/package_augmentation/ros_ament_python.py", line 57, in getter\n    return get_setup_information(\n  File "/usr/lib/python3/dist-packages/colcon_python_setup_py/package_identification/python_setup_py.py", line 241, in get_setup_information\n    _setup_information_cache[hashable_env] = _get_setup_information(\n  File "/usr/lib/python3/dist-packages/colcon_python_setup_py/package_identification/python_setup_py.py", line 288, in _get_setup_information\n    result = subprocess.run(\n  File "/usr/lib/python3.10/subprocess.py", line 526, in run\n    raise CalledProcessError(retcode, process.args,\nsubprocess.CalledProcessError: Command \'[\'/usr/bin/python3\', \'-c\', \'import sys;from contextlib import suppress;exec("with suppress(ImportError):    from setuptools.extern.packaging.specifiers    import SpecifierSet");exec("with suppress(ImportError):    from packaging.specifiers import SpecifierSet");from distutils.core import run_setup;dist = run_setup(    \\\'setup.py\\\', script_args=(\\\'--dry-run\\\',), stop_after=\\\'config\\\');skip_keys = (\\\'cmdclass\\\', \\\'distclass\\\', \\\'ext_modules\\\', \\\'metadata\\\');data = {    key: value for key, value in dist.__dict__.items()     if (        not key.startswith(\\\'_\\\') and         not callable(value) and         key not in skip_keys and         key not in dist.display_option_names    )};data[\\\'metadata\\\'] = {    k: v for k, v in dist.metadata.__dict__.items()     if k not in (\\\'license_files\\\', \\\'provides_extras\\\')};sys.stdout.buffer.write(repr(data).encode(\\\'utf-8\\\'))\']\' returned non-zero exit status 1.\n'}
[1.465290] (follow_objects) JobEnded: {'identifier': 'follow_objects', 'rc': 1}
[1.474930] (-) EventReactorShutdown: {}
